import {useState} from 'react';
import type {RecordInput,VerificationRecord} from '../lib/records.server';
export function RecordEditor({initial=[],available=[],selected}: {initial?:RecordInput[];available?:VerificationRecord[];selected?:string[]}) {
 const [rows,setRows]=useState(initial);
 const [retained,setRetained]=useState(selected ?? available.map(r=>r.id));
 const edit=(i:number,key:keyof RecordInput,value:string|number)=>setRows(rows.map((r,j)=>j===i?{...r,[key]:value}:r));
 const add=()=>setRows([...rows,{api_path:'',api_kind:'function',tag:'no-panic',api_safety:'safe',contract_language:'rust',contract:'',configuration:'default features; x86_64-unknown-linux-gnu',run_index:0,result_index:0}]);
 return <section className="form-section"><h2>API verification results</h2><p>Both properties may be attached to one API. Mark unsafe functions explicitly and paste contract source, not prose. Evidence numbers start at 1.</p>
 <input type="hidden" name="records" value={JSON.stringify(rows)}/><input type="hidden" name="inherited" value={JSON.stringify(retained)}/>
 {available.length>0&&<fieldset><legend>Retain results from the source publication</legend>{available.map(r=><div className="inherit-row" key={r.id}><label><input type="checkbox" checked={retained.includes(r.id)} onChange={e=>setRetained(e.target.checked?[...retained,r.id]:retained.filter(id=>id!==r.id))}/><code>{r.api_path}</code> · {r.tag} · {r.publisher_login}</label><button type="button" className="auth-button" disabled={rows.some(row=>row.supersedes_id===r.id)} onClick={()=>{setRetained(retained.filter(id=>id!==r.id));setRows([...rows,{api_path:r.api_path,api_kind:r.api_kind,tag:r.tag,api_safety:r.api_safety==='unknown'?'safe':r.api_safety,contract_language:r.contract_language==='legacy'?'rust':r.contract_language,contract:r.contract_language==='legacy'?'':r.contract,configuration:r.configuration,run_index:0,result_index:0,supersedes_id:r.id}]);}}>Replace with new evidence</button></div>)}</fieldset>}
 {rows.map((r,i)=><fieldset className="record-editor" key={i}><legend>Result {i+1}{r.supersedes_id?' · revision':''}</legend><div className="form-grid">
 <label>Public API path<input required value={r.api_path} onChange={e=>edit(i,'api_path',e.target.value)} placeholder="fnv::FnvHasher::write"/></label>
 <label>Kind<select value={r.api_kind} onChange={e=>edit(i,'api_kind',e.target.value)}><option value="function">Function</option><option value="method">Method</option></select></label>
 <label>API safety<select value={r.api_safety} onChange={e=>{const safety=e.target.value as 'safe'|'unsafe';setRows(rows.map((row,j)=>j===i?{...row,api_safety:safety,contract:safety==='safe'&&row.tag==='no-ub'?'':row.contract}:row));}}><option value="safe">safe fn</option><option value="unsafe">unsafe fn — caller safety obligations</option></select></label>
 <label>Property<select value={r.tag} onChange={e=>setRows(rows.map((row,j)=>j===i?{...row,tag:e.target.value as 'no-ub'|'no-panic',contract:e.target.value==='no-ub'&&row.api_safety==='safe'?'':row.contract}:row))}><option value="no-panic">no panic</option><option value="no-ub">no UB</option></select></label>
 <label>Build configuration<input required value={r.configuration} onChange={e=>edit(i,'configuration',e.target.value)}/></label>
 {r.api_safety==='safe'&&r.tag==='no-ub'?<p className="form-field-wide">No additional safety preconditions for this safe API.</p>:<><label>Contract language<select value={r.contract_language} onChange={e=>edit(i,'contract_language',e.target.value)}><option value="rust">Rust</option><option value="kani">Kani / Rust</option><option value="verus">Verus</option><option value="creusot">Creusot / Pearlite</option></select></label><label className="form-field-wide">Contract source code<textarea required={r.api_safety==='unsafe'} rows={6} spellCheck={false} className="contract-code" value={r.contract} onChange={e=>edit(i,'contract',e.target.value)} placeholder="Paste the actual requires / assume / contract source. Leave empty only for an unconditional safe API claim."/></label></>}

 <label>SARIF run number<input type="number" min={1} required value={r.run_index+1} onChange={e=>edit(i,'run_index',Number(e.target.value)-1)}/></label><label>Result number in run<input type="number" min={1} required value={r.result_index+1} onChange={e=>edit(i,'result_index',Number(e.target.value)-1)}/></label>
 </div><button className="auth-button" type="button" onClick={()=>setRows([...rows,{...r,tag:r.tag==='no-ub'?'no-panic':'no-ub',contract:r.api_safety==='safe'?'':r.contract,supersedes_id:undefined}])}>+ Add {r.tag==='no-ub'?'no panic':'no UB'} for this API</button> <button className="auth-button" type="button" onClick={()=>setRows(rows.filter((_,j)=>i!==j))}>Remove result</button></fieldset>)}
 <button className="auth-button" type="button" onClick={add}>+ Add API result</button><p className="form-note">Tags are publisher assertions under the stated contracts. The site does not rerun verification.</p></section>;
}
