PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY,github_id INTEGER NOT NULL UNIQUE,username TEXT NOT NULL UNIQUE,bio TEXT NOT NULL DEFAULT '' CHECK(length(CAST(bio AS BLOB))<=500),role TEXT NOT NULL DEFAULT 'user',status TEXT NOT NULL DEFAULT 'active',accepted_terms_version TEXT NOT NULL,terms_accepted_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,csrf TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE oauth_flows(state_hash TEXT PRIMARY KEY,verifier TEXT NOT NULL,terms_version TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE email_contacts(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,address TEXT,verified_at TEXT,delivery_status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE notification_preferences(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,replies INTEGER NOT NULL DEFAULT 1,claim_comments INTEGER NOT NULL DEFAULT 1);
CREATE TABLE crates(id INTEGER PRIMARY KEY,registry TEXT NOT NULL DEFAULT 'crates.io',name TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '');
CREATE TABLE releases(id INTEGER PRIMARY KEY,crate_id INTEGER NOT NULL REFERENCES crates(id),version TEXT NOT NULL,checksum TEXT,yanked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,UNIQUE(crate_id,version));
CREATE TABLE doc_snapshots(release_id INTEGER PRIMARY KEY REFERENCES releases(id),target TEXT,features_json TEXT,rustdoc_format INTEGER NOT NULL,rustc_version TEXT,source_url TEXT NOT NULL,source_hash TEXT NOT NULL,r2_key TEXT NOT NULL,imported_at TEXT NOT NULL);
CREATE TABLE api_items(id TEXT PRIMARY KEY,release_id INTEGER NOT NULL REFERENCES releases(id),canonical_key TEXT NOT NULL,display_path TEXT NOT NULL,kind TEXT NOT NULL,is_unsafe INTEGER NOT NULL,signature TEXT NOT NULL,upstream_url TEXT NOT NULL,UNIQUE(release_id,canonical_key));
CREATE TABLE import_jobs(id TEXT PRIMARY KEY,release_id INTEGER NOT NULL REFERENCES releases(id),requested_by TEXT REFERENCES users(id) ON DELETE SET NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,error_code TEXT,next_retry_at TEXT,lease_until TEXT,created_at TEXT NOT NULL);
CREATE UNIQUE INDEX one_active_import ON import_jobs(release_id) WHERE status IN ('pending','running','retry');
CREATE TABLE tools(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,official_url TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE tool_versions(id TEXT PRIMARY KEY,tool_id TEXT NOT NULL REFERENCES tools(id),version TEXT NOT NULL,selectable INTEGER NOT NULL DEFAULT 1,UNIQUE(tool_id,version));
CREATE TABLE claims(id INTEGER PRIMARY KEY AUTOINCREMENT,create_key TEXT NOT NULL UNIQUE,api_item_id TEXT NOT NULL REFERENCES api_items(id),property TEXT NOT NULL CHECK(property IN ('panic_contract','no_ub')),author_id TEXT REFERENCES users(id) ON DELETE SET NULL,visibility TEXT NOT NULL DEFAULT 'public',withdrawn_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE claim_revisions(claim_id INTEGER NOT NULL REFERENCES claims(id),revision_no INTEGER NOT NULL,title TEXT NOT NULL,precondition TEXT NOT NULL,explanation TEXT NOT NULL,trusted_assumptions TEXT NOT NULL,tool_version_id TEXT NOT NULL REFERENCES tool_versions(id),environment TEXT NOT NULL,evidence_url TEXT NOT NULL,limitations TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(claim_id,revision_no));
CREATE TABLE comments(id TEXT PRIMARY KEY,claim_id INTEGER NOT NULL REFERENCES claims(id),sequence_no INTEGER NOT NULL,revision_no INTEGER NOT NULL,author_id TEXT REFERENCES users(id) ON DELETE SET NULL,reply_to_id TEXT REFERENCES comments(id),body TEXT,edit_version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,edited_at TEXT,deleted_at TEXT,visibility TEXT NOT NULL DEFAULT 'public',UNIQUE(claim_id,sequence_no),FOREIGN KEY(claim_id,revision_no) REFERENCES claim_revisions(claim_id,revision_no));
CREATE INDEX comment_tree ON comments(claim_id,reply_to_id,created_at,id);
CREATE INDEX comment_author ON comments(author_id,created_at,id);
CREATE INDEX claim_author ON claims(author_id,created_at);
CREATE INDEX claim_api ON claims(api_item_id,property,created_at);
CREATE TABLE comment_history(comment_id TEXT NOT NULL REFERENCES comments(id),history_no INTEGER NOT NULL,action TEXT NOT NULL,body TEXT,actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,PRIMARY KEY(comment_id,history_no));
CREATE TABLE comment_votes(comment_id TEXT NOT NULL REFERENCES comments(id),user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,value INTEGER NOT NULL CHECK(value IN (-1,1)),updated_at TEXT NOT NULL,PRIMARY KEY(comment_id,user_id));
CREATE TABLE accepts(claim_id INTEGER NOT NULL,revision_no INTEGER NOT NULL,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TEXT NOT NULL,PRIMARY KEY(claim_id,revision_no,user_id),FOREIGN KEY(claim_id,revision_no) REFERENCES claim_revisions(claim_id,revision_no));
CREATE TABLE idempotency_keys(user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,operation TEXT NOT NULL,key TEXT NOT NULL,request_hash TEXT NOT NULL,resource_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,operation,key));
CREATE TABLE outbox_events(id TEXT PRIMARY KEY,type TEXT NOT NULL,aggregate_id TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,created_at TEXT NOT NULL,enqueued_at TEXT,completed_at TEXT);
CREATE TABLE email_deliveries(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES outbox_events(id),user_id TEXT REFERENCES users(id) ON DELETE SET NULL,category TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,provider_id TEXT UNIQUE,next_attempt_at TEXT,sending_at TEXT,attempt_token TEXT,sent_address TEXT,created_at TEXT NOT NULL,UNIQUE(event_id,user_id));
CREATE TABLE email_delivery_events(event_id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,delivery_id TEXT REFERENCES email_deliveries(id),type TEXT NOT NULL,event_at TEXT NOT NULL,processed_at TEXT);
CREATE TABLE email_suppressions(address TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TABLE audit_events(id TEXT PRIMARY KEY,actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE rate_limits(subject TEXT NOT NULL,kind TEXT NOT NULL,bucket TEXT NOT NULL,used INTEGER NOT NULL,lim INTEGER NOT NULL,CHECK(used<=lim),PRIMARY KEY(subject,kind,bucket));
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE transaction_checks(ok INTEGER NOT NULL CHECK(ok=1));
CREATE TABLE maintenance(id INTEGER PRIMARY KEY CHECK(id=1));
CREATE TABLE erasures(user_id TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TRIGGER fixed_claim BEFORE UPDATE OF api_item_id,property ON claims WHEN NEW.api_item_id<>OLD.api_item_id OR NEW.property<>OLD.property BEGIN SELECT RAISE(ABORT,'immutable_target'); END;
CREATE TRIGGER fixed_author BEFORE UPDATE OF author_id ON claims WHEN NEW.author_id IS NOT NULL AND NEW.author_id IS NOT OLD.author_id BEGIN SELECT RAISE(ABORT,'immutable_author'); END;
CREATE TRIGGER revision_update BEFORE UPDATE ON claim_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER revision_delete BEFORE DELETE ON claim_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER comment_parent BEFORE INSERT ON comments WHEN NEW.reply_to_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM comments WHERE id=NEW.reply_to_id AND claim_id=NEW.claim_id) BEGIN SELECT RAISE(ABORT,'invalid_parent'); END;
CREATE TRIGGER fixed_comment BEFORE UPDATE OF reply_to_id,claim_id,revision_no ON comments WHEN NEW.reply_to_id IS NOT OLD.reply_to_id OR NEW.claim_id<>OLD.claim_id OR NEW.revision_no<>OLD.revision_no BEGIN SELECT RAISE(ABORT,'immutable_comment_target'); END;
CREATE TRIGGER no_self_vote BEFORE INSERT ON comment_votes WHEN EXISTS(SELECT 1 FROM comments WHERE id=NEW.comment_id AND (author_id=NEW.user_id OR deleted_at IS NOT NULL OR visibility<>'public')) BEGIN SELECT RAISE(ABORT,'vote_forbidden'); END;
CREATE TRIGGER no_self_vote_update BEFORE UPDATE ON comment_votes WHEN EXISTS(SELECT 1 FROM comments WHERE id=NEW.comment_id AND (author_id=NEW.user_id OR deleted_at IS NOT NULL OR visibility<>'public')) BEGIN SELECT RAISE(ABORT,'vote_forbidden'); END;
CREATE TRIGGER no_self_accept BEFORE INSERT ON accepts WHEN EXISTS(SELECT 1 FROM claims WHERE id=NEW.claim_id AND author_id=NEW.user_id) BEGIN SELECT RAISE(ABORT,'self_accept'); END;
CREATE VIEW karma_v1 AS SELECT author_id,COUNT(*) score FROM (SELECT DISTINCT c.author_id,a.claim_id,a.user_id FROM accepts a JOIN claims c ON c.id=a.claim_id WHERE c.visibility='public' AND c.withdrawn_at IS NULL AND c.author_id IS NOT NULL AND c.author_id<>a.user_id) GROUP BY author_id;
