PRAGMA foreign_keys=ON;
CREATE TABLE users(id TEXT PRIMARY KEY,github_id INTEGER NOT NULL UNIQUE,username TEXT NOT NULL UNIQUE,role TEXT NOT NULL DEFAULT 'user',status TEXT NOT NULL DEFAULT 'active',accepted_terms_version TEXT NOT NULL,terms_accepted_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,csrf TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE oauth_flows(state_hash TEXT PRIMARY KEY,verifier TEXT NOT NULL,terms_version TEXT NOT NULL,expires_at TEXT NOT NULL);
CREATE TABLE email_contacts(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,address TEXT,verified_at TEXT,delivery_status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE notification_preferences(user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,replies INTEGER NOT NULL DEFAULT 1,report_comments INTEGER NOT NULL DEFAULT 1);
CREATE TABLE crates(id INTEGER PRIMARY KEY,registry TEXT NOT NULL DEFAULT 'crates.io',name TEXT NOT NULL UNIQUE,description TEXT NOT NULL DEFAULT '');
CREATE TABLE releases(id INTEGER PRIMARY KEY,crate_id INTEGER NOT NULL REFERENCES crates(id),version TEXT NOT NULL,checksum TEXT,yanked INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,UNIQUE(crate_id,version));
CREATE TABLE doc_snapshots(release_id INTEGER PRIMARY KEY REFERENCES releases(id),target TEXT,features_json TEXT,rustdoc_format INTEGER NOT NULL,rustc_version TEXT,source_url TEXT NOT NULL,source_hash TEXT NOT NULL,r2_key TEXT NOT NULL,imported_at TEXT NOT NULL);
CREATE TABLE api_items(id TEXT PRIMARY KEY,release_id INTEGER NOT NULL REFERENCES releases(id),canonical_key TEXT NOT NULL,display_path TEXT NOT NULL,kind TEXT NOT NULL,is_unsafe INTEGER NOT NULL,signature TEXT NOT NULL,upstream_url TEXT NOT NULL,UNIQUE(release_id,canonical_key));
CREATE TABLE import_jobs(id TEXT PRIMARY KEY,release_id INTEGER NOT NULL REFERENCES releases(id),requested_by TEXT REFERENCES users(id) ON DELETE SET NULL,status TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,error_code TEXT,next_retry_at TEXT,lease_until TEXT,created_at TEXT NOT NULL);
CREATE UNIQUE INDEX one_active_import ON import_jobs(release_id) WHERE status IN ('pending','running','retry');
CREATE TABLE tools(id TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,official_url TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE tool_versions(id TEXT PRIMARY KEY,tool_id TEXT NOT NULL REFERENCES tools(id),version TEXT NOT NULL,selectable INTEGER NOT NULL DEFAULT 1,UNIQUE(tool_id,version));
CREATE TABLE idempotency_keys(user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,operation TEXT NOT NULL,key TEXT NOT NULL,request_hash TEXT NOT NULL,resource_id TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(user_id,operation,key));
CREATE TABLE outbox_events(id TEXT PRIMARY KEY,type TEXT NOT NULL,aggregate_id TEXT NOT NULL,dedupe_key TEXT NOT NULL UNIQUE,payload TEXT NOT NULL,created_at TEXT NOT NULL,enqueued_at TEXT,completed_at TEXT);
CREATE TABLE email_deliveries(id TEXT PRIMARY KEY,event_id TEXT NOT NULL REFERENCES outbox_events(id),user_id TEXT REFERENCES users(id) ON DELETE SET NULL,category TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,provider_id TEXT UNIQUE,next_attempt_at TEXT,sending_at TEXT,attempt_token TEXT,sent_address TEXT,created_at TEXT NOT NULL,UNIQUE(event_id,user_id));
CREATE TABLE email_delivery_events(event_id TEXT PRIMARY KEY,provider_id TEXT NOT NULL,delivery_id TEXT REFERENCES email_deliveries(id),type TEXT NOT NULL,event_at TEXT NOT NULL,processed_at TEXT);
CREATE TABLE email_suppressions(address TEXT PRIMARY KEY,created_at TEXT NOT NULL);
CREATE TABLE audit_events(id TEXT PRIMARY KEY,actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,action TEXT NOT NULL,target_id TEXT NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE rate_limits(subject TEXT NOT NULL,kind TEXT NOT NULL,bucket TEXT NOT NULL,used INTEGER NOT NULL,lim INTEGER NOT NULL,CHECK(used<=lim),PRIMARY KEY(subject,kind,bucket));
CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE transaction_checks(ok INTEGER NOT NULL CHECK(ok=1));
CREATE TABLE maintenance(id INTEGER PRIMARY KEY CHECK(id=1));
CREATE TABLE erasures(user_id TEXT PRIMARY KEY,created_at TEXT NOT NULL);

CREATE TABLE reports(id INTEGER PRIMARY KEY AUTOINCREMENT,create_key TEXT NOT NULL UNIQUE,release_id INTEGER NOT NULL REFERENCES releases(id),author_id TEXT REFERENCES users(id) ON DELETE SET NULL,visibility TEXT NOT NULL DEFAULT 'public',withdrawn_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE report_revisions(report_id INTEGER NOT NULL REFERENCES reports(id),revision_no INTEGER NOT NULL,title TEXT NOT NULL,explanation TEXT NOT NULL,trusted_assumptions TEXT NOT NULL,tool_version_id TEXT NOT NULL REFERENCES tool_versions(id),environment TEXT NOT NULL,evidence_url TEXT NOT NULL,limitations TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(report_id,revision_no));
CREATE TABLE claims(id TEXT PRIMARY KEY,report_id INTEGER NOT NULL REFERENCES reports(id),api_item_id TEXT NOT NULL REFERENCES api_items(id),property TEXT NOT NULL CHECK(property IN ('panic_contract','no_ub')),created_at TEXT NOT NULL,UNIQUE(id,report_id));
CREATE TABLE claim_revisions(claim_id TEXT NOT NULL,report_id INTEGER NOT NULL,report_revision INTEGER NOT NULL,position INTEGER NOT NULL,title TEXT NOT NULL,precondition TEXT NOT NULL,explanation TEXT NOT NULL,trusted_assumptions TEXT NOT NULL,evidence_url TEXT NOT NULL,limitations TEXT NOT NULL,PRIMARY KEY(claim_id,report_revision),UNIQUE(report_id,report_revision,position),FOREIGN KEY(claim_id,report_id) REFERENCES claims(id,report_id),FOREIGN KEY(report_id,report_revision) REFERENCES report_revisions(report_id,revision_no));
CREATE TABLE report_stars(report_id INTEGER NOT NULL REFERENCES reports(id),user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TEXT NOT NULL,PRIMARY KEY(report_id,user_id));
CREATE TABLE claim_stars(claim_id TEXT NOT NULL REFERENCES claims(id),user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TEXT NOT NULL,PRIMARY KEY(claim_id,user_id));
CREATE TABLE report_comments(id TEXT PRIMARY KEY,report_id INTEGER NOT NULL REFERENCES reports(id),sequence_no INTEGER NOT NULL,revision_no INTEGER NOT NULL,author_id TEXT REFERENCES users(id) ON DELETE SET NULL,reply_to_id TEXT REFERENCES report_comments(id),body TEXT,edit_version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,edited_at TEXT,deleted_at TEXT,visibility TEXT NOT NULL DEFAULT 'public',UNIQUE(report_id,sequence_no),FOREIGN KEY(report_id,revision_no) REFERENCES report_revisions(report_id,revision_no));
CREATE TABLE report_comment_history(comment_id TEXT NOT NULL REFERENCES report_comments(id),history_no INTEGER NOT NULL,action TEXT NOT NULL,body TEXT,actor_id TEXT REFERENCES users(id) ON DELETE SET NULL,created_at TEXT NOT NULL,PRIMARY KEY(comment_id,history_no));
CREATE TABLE report_comment_votes(comment_id TEXT NOT NULL REFERENCES report_comments(id),user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,value INTEGER NOT NULL CHECK(value IN (-1,1)),updated_at TEXT NOT NULL,PRIMARY KEY(comment_id,user_id));
CREATE INDEX report_author ON reports(author_id,created_at,id);
CREATE INDEX report_release ON reports(release_id,created_at,id);
CREATE INDEX claim_api ON claims(api_item_id,report_id);
CREATE INDEX comment_tree ON report_comments(report_id,reply_to_id,sequence_no);
CREATE INDEX comment_author ON report_comments(author_id,created_at,id);
CREATE TRIGGER fixed_report BEFORE UPDATE OF release_id,author_id ON reports WHEN NEW.release_id<>OLD.release_id OR (NEW.author_id IS NOT NULL AND NEW.author_id IS NOT OLD.author_id) BEGIN SELECT RAISE(ABORT,'immutable_report'); END;
CREATE TRIGGER fixed_claim BEFORE UPDATE ON claims BEGIN SELECT RAISE(ABORT,'immutable_claim'); END;
CREATE TRIGGER claim_release BEFORE INSERT ON claims WHEN NOT EXISTS(SELECT 1 FROM reports p JOIN api_items a ON a.release_id=p.release_id WHERE p.id=NEW.report_id AND a.id=NEW.api_item_id) BEGIN SELECT RAISE(ABORT,'invalid_claim_release'); END;
CREATE TRIGGER comment_parent BEFORE INSERT ON report_comments WHEN NEW.reply_to_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM report_comments WHERE id=NEW.reply_to_id AND report_id=NEW.report_id) BEGIN SELECT RAISE(ABORT,'invalid_parent'); END;
CREATE TRIGGER fixed_comment BEFORE UPDATE OF reply_to_id,report_id,revision_no ON report_comments WHEN NEW.reply_to_id IS NOT OLD.reply_to_id OR NEW.report_id<>OLD.report_id OR NEW.revision_no<>OLD.revision_no BEGIN SELECT RAISE(ABORT,'immutable_comment_target'); END;
CREATE VIEW karma_v1 AS SELECT p.author_id,COUNT(*) score FROM report_stars s JOIN reports p ON p.id=s.report_id WHERE p.visibility='public' AND p.withdrawn_at IS NULL AND p.author_id IS NOT NULL AND p.author_id<>s.user_id GROUP BY p.author_id;
CREATE TRIGGER report_revisions_update BEFORE UPDATE ON report_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER report_revisions_delete BEFORE DELETE ON report_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER claim_revisions_update BEFORE UPDATE ON claim_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER claim_revisions_delete BEFORE DELETE ON claim_revisions WHEN NOT EXISTS(SELECT 1 FROM maintenance) BEGIN SELECT RAISE(ABORT,'immutable_revision'); END;
CREATE TRIGGER no_self_vote_insert BEFORE INSERT ON report_comment_votes WHEN EXISTS(SELECT 1 FROM report_comments WHERE id=NEW.comment_id AND (author_id=NEW.user_id OR deleted_at IS NOT NULL OR visibility<>'public')) BEGIN SELECT RAISE(ABORT,'vote_forbidden'); END;
CREATE TRIGGER no_self_vote_update BEFORE UPDATE ON report_comment_votes WHEN EXISTS(SELECT 1 FROM report_comments WHERE id=NEW.comment_id AND (author_id=NEW.user_id OR deleted_at IS NOT NULL OR visibility<>'public')) BEGIN SELECT RAISE(ABORT,'vote_forbidden'); END;
