// Generated by scripts/build-tool-docs.mjs; edit content/tool-docs instead.
export const documents: Record<string, {revision:number;date:string;summary:string;markdown:string}[]> = {
  "kani": [
    {
      "revision": 1,
      "date": "2026-09-22",
      "summary": "Initial scope and limitations documentation",
      "markdown": "## Verification scope\n\nKani checks executions reachable from the selected harness under its assumptions. A successful run is evidence for that scope, not a claim about every configuration or every invocation of an API. Harness inputs, `kani::assume`, function preconditions and stubs can restrict the scope.\n\n## Checks and bounds\n\nThe enabled checks, loop and recursion bounds, and unwinding assertions matter. Suppressing a check or bypassing an unwinding failure does not establish the corresponding unrestricted claim. Record non-default options and restrictions in the report.\n\n## Undefined behavior\n\nKani detects supported classes of undefined behavior in its model. Rust support and the modeled environment have limitations; a successful run must not be interpreted as coverage of all Rust behavior or every possible platform.\n\n## Contracts and trusted components\n\nA `proof_for_contract` harness checks a function under its preconditions. Stubs, assumed contracts, compiler behavior and library models contribute to the trusted assumptions. The presence of a contract attribute in source does not establish that verification succeeded.\n\n## Environment\n\nResults apply to the checked target, features, dependencies and tool version. Report-specific assumptions and limitations remain part of the report and are not replaced by these notes.\n\n## References\n\n- [Kani limitations](https://model-checking.github.io/kani/limitations.html)\n- [Function contracts](https://model-checking.github.io/kani/reference/experimental/contracts.html)\n- [Kani documentation](https://model-checking.github.io/kani/)"
    }
  ],
  "demo": [
    {
      "revision": 1,
      "date": "2026-09-22",
      "summary": "Identify synthetic staging tools and reports",
      "markdown": "## Synthetic demonstration data\n\nThis tool entry and its versions exist only to illustrate the staging UI. Reports using it are synthetic examples, not verification results. Their stated guarantees must not be used as evidence about real software.\n\n## Scope\n\nThe example reports demonstrate how preconditions, trusted assumptions, evidence and report-specific limitations are presented. Register an actual tool with reviewed, tool-specific documentation before publishing real verification reports."
    }
  ]
};
