[book]
title = "proofs.rs Book"
language = "en"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "light"
site-url = "/book/"
no-section-label = true
smart-punctuation = false

[output.html.playground]
runnable = false

[output.html.print]
enable = false
